//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFatureClient.wsContrato {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contrato", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Contrato : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDPRODUTOField;
        
        private int IDPROCESSOField;
        
        private double QUANTIDADEField;
        
        private System.DateTime VALIDADEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPLEMENTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IDPRODUTO {
            get {
                return this.IDPRODUTOField;
            }
            set {
                if ((this.IDPRODUTOField.Equals(value) != true)) {
                    this.IDPRODUTOField = value;
                    this.RaisePropertyChanged("IDPRODUTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int IDPROCESSO {
            get {
                return this.IDPROCESSOField;
            }
            set {
                if ((this.IDPROCESSOField.Equals(value) != true)) {
                    this.IDPROCESSOField = value;
                    this.RaisePropertyChanged("IDPROCESSO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double QUANTIDADE {
            get {
                return this.QUANTIDADEField;
            }
            set {
                if ((this.QUANTIDADEField.Equals(value) != true)) {
                    this.QUANTIDADEField = value;
                    this.RaisePropertyChanged("QUANTIDADE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime VALIDADE {
            get {
                return this.VALIDADEField;
            }
            set {
                if ((this.VALIDADEField.Equals(value) != true)) {
                    this.VALIDADEField = value;
                    this.RaisePropertyChanged("VALIDADE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string COMPLEMENTO {
            get {
                return this.COMPLEMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPLEMENTOField, value) != true)) {
                    this.COMPLEMENTOField = value;
                    this.RaisePropertyChanged("COMPLEMENTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsContrato.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AppFatureClient.wsContrato.HelloWorldResponse HelloWorld(AppFatureClient.wsContrato.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Soma", ReplyAction="*")]
        int Soma(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNow", ReplyAction="*")]
        System.DateTime GetNow();
        
        // CODEGEN: Generating message contract since element name CNPJ from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContract", ReplyAction="*")]
        AppFatureClient.wsContrato.GetContractResponse GetContract(AppFatureClient.wsContrato.GetContractRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AppFatureClient.wsContrato.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AppFatureClient.wsContrato.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppFatureClient.wsContrato.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AppFatureClient.wsContrato.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContract", Namespace="http://tempuri.org/", Order=0)]
        public AppFatureClient.wsContrato.GetContractRequestBody Body;
        
        public GetContractRequest() {
        }
        
        public GetContractRequest(AppFatureClient.wsContrato.GetContractRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContractRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CNPJ;
        
        public GetContractRequestBody() {
        }
        
        public GetContractRequestBody(string CNPJ) {
            this.CNPJ = CNPJ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContractResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppFatureClient.wsContrato.GetContractResponseBody Body;
        
        public GetContractResponse() {
        }
        
        public GetContractResponse(AppFatureClient.wsContrato.GetContractResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContractResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppFatureClient.wsContrato.Contrato[] GetContractResult;
        
        public GetContractResponseBody() {
        }
        
        public GetContractResponseBody(AppFatureClient.wsContrato.Contrato[] GetContractResult) {
            this.GetContractResult = GetContractResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : AppFatureClient.wsContrato.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<AppFatureClient.wsContrato.ServiceSoap>, AppFatureClient.wsContrato.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppFatureClient.wsContrato.HelloWorldResponse AppFatureClient.wsContrato.ServiceSoap.HelloWorld(AppFatureClient.wsContrato.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AppFatureClient.wsContrato.HelloWorldRequest inValue = new AppFatureClient.wsContrato.HelloWorldRequest();
            inValue.Body = new AppFatureClient.wsContrato.HelloWorldRequestBody();
            AppFatureClient.wsContrato.HelloWorldResponse retVal = ((AppFatureClient.wsContrato.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        public int Soma(int a, int b) {
            return base.Channel.Soma(a, b);
        }
        
        public System.DateTime GetNow() {
            return base.Channel.GetNow();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppFatureClient.wsContrato.GetContractResponse AppFatureClient.wsContrato.ServiceSoap.GetContract(AppFatureClient.wsContrato.GetContractRequest request) {
            return base.Channel.GetContract(request);
        }
        
        public AppFatureClient.wsContrato.Contrato[] GetContract(string CNPJ) {
            AppFatureClient.wsContrato.GetContractRequest inValue = new AppFatureClient.wsContrato.GetContractRequest();
            inValue.Body = new AppFatureClient.wsContrato.GetContractRequestBody();
            inValue.Body.CNPJ = CNPJ;
            AppFatureClient.wsContrato.GetContractResponse retVal = ((AppFatureClient.wsContrato.ServiceSoap)(this)).GetContract(inValue);
            return retVal.Body.GetContractResult;
        }
    }
}
