using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using DevExpress.XtraReports.UI;

namespace AppFatureClient
{
    public partial class RelTabPrecoRevendaSipi : DevExpress.XtraReports.UI.XtraReport
    {
        public string codRPR = string.Empty;

        public RelTabPrecoRevendaSipi()
        {
            InitializeComponent();
        }

        private void Detail_BeforePrint(object sender, System.Drawing.Printing.PrintEventArgs e)
        {
           
        }

        private void ReportHeader_BeforePrint(object sender, System.Drawing.Printing.PrintEventArgs e)
        {

        }

        private void ReportHeader_BeforePrint_1(object sender, System.Drawing.Printing.PrintEventArgs e)
        {
            string sSql = @"SELECT IMAGEM FROM GIMAGEM WHERE ID = (SELECT IDIMAGEM FROM GCOLIGADA WHERE CODCOLIGADA = ?)";
            sSql = AppLib.Context.poolConnection.Get().ParseCommand(sSql, new Object[] { AppLib.Context.Empresa });

            byte[] arrayimagem = (byte[])AppLib.Context.poolConnection.Get().ExecGetField(null, sSql, new Object[] { });
            System.IO.MemoryStream ms = new System.IO.MemoryStream(arrayimagem);
            xrPictureBox1.Image = Image.FromStream(ms);     
        }

        private void DetailReport_BeforePrint(object sender, System.Drawing.Printing.PrintEventArgs e)
        {
            System.Data.DataTable dt = AppLib.Context.poolConnection.Get().ExecQuery(@"SELECT
	TMOVCOMPL.CODPRDREVENDA,
	UPPER(TMOVCOMPL.DESCRICAOPRDREVENDA) DESCRICAO_PRD,
	TMOV.VALORLIQUIDOORIG - ISNULL((SELECT SUM(VALOR) VALOR FROM TTRBMOV WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND IDMOV = TMOV.IDMOV AND CODTRB = 'IPI'),0) VALORLIQUIDOORIG,

	ISNULL((SELECT PERCDESCONTO FROM ZREPREDESC WHERE CODREPRESENTANTE = ? AND CODTB4FAT IN(
	SELECT DISTINCT(SUBSTRING(CODIGOPRD,1,10)) FROM TPRODUTO WHERE IDPRD IN 
	(SELECT IDPRD FROM TITMMOV WHERE NSEQITMMOV IN (
	SELECT NSEQITMMOV FROM TITMMOVCOMPL WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND IDMOV = TMOV.IDMOV AND TITMMOVCOMPL.PRDREVENDA = 'SIM')
	AND CODCOLIGADA = TMOV.CODCOLIGADA
	AND IDMOV = TMOV.IDMOV))
	AND CODCOLIGADA = TMOV.CODCOLIGADA),0) PERC_DESC ,
	
	((TMOV.VALORLIQUIDOORIG - ISNULL((SELECT SUM(VALOR) VALOR FROM TTRBMOV WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND IDMOV = TMOV.IDMOV AND CODTRB = 'IPI'),0)) *
	(ISNULL((SELECT PERCDESCONTO FROM ZREPREDESC WHERE CODREPRESENTANTE = ? AND CODTB4FAT IN(
	SELECT DISTINCT(SUBSTRING(CODIGOPRD,1,10)) FROM TPRODUTO WHERE IDPRD IN 
	(SELECT IDPRD FROM TITMMOV WHERE NSEQITMMOV IN (
	SELECT NSEQITMMOV FROM TITMMOVCOMPL WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND IDMOV = TMOV.IDMOV AND TITMMOVCOMPL.PRDREVENDA = 'SIM')
	AND CODCOLIGADA = TMOV.CODCOLIGADA
	AND IDMOV = TMOV.IDMOV))
	AND CODCOLIGADA = TMOV.CODCOLIGADA),0))/100) VALOR_DESC,
		
	((TMOV.VALORLIQUIDOORIG - ISNULL((SELECT SUM(VALOR) VALOR FROM TTRBMOV WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND IDMOV = TMOV.IDMOV AND CODTRB = 'IPI'),0)) -
	(TMOV.VALORLIQUIDOORIG *
	(ISNULL((SELECT PERCDESCONTO FROM ZREPREDESC WHERE CODREPRESENTANTE = ? AND CODTB4FAT IN(
	SELECT DISTINCT(SUBSTRING(CODIGOPRD,1,10)) FROM TPRODUTO WHERE IDPRD IN 
	(SELECT IDPRD FROM TITMMOV WHERE NSEQITMMOV IN (
	SELECT NSEQITMMOV FROM TITMMOVCOMPL WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND IDMOV = TMOV.IDMOV AND TITMMOVCOMPL.PRDREVENDA = 'SIM')
	AND CODCOLIGADA = TMOV.CODCOLIGADA
	AND IDMOV = TMOV.IDMOV))
	AND CODCOLIGADA = TMOV.CODCOLIGADA),0))/100))  VALOR_COM_DESCONTO,

	
	ISNULL((SELECT ALIQUOTA FROM TTRBPRD WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND CODTRB = 'IPI' AND IDPRD IN 
	(SELECT IDPRD FROM TITMMOV WHERE NSEQITMMOV IN (
	SELECT NSEQITMMOV FROM TITMMOVCOMPL WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND IDMOV = TMOV.IDMOV AND TITMMOVCOMPL.PRDREVENDA = 'SIM')
	AND CODCOLIGADA = TMOV.CODCOLIGADA
	AND IDMOV = TMOV.IDMOV)),0) ALIQ_IPI,

	ISNULL((SELECT SUM(VALOR) VALOR FROM TTRBMOV WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND IDMOV = TMOV.IDMOV AND CODTRB = 'IPI'),0) IPI,
	
	(SELECT CODIGOPRD FROM TPRODUTO WHERE CODCOLPRD = TMOV.CODCOLIGADA AND IDPRD IN 
	(SELECT IDPRD FROM TITMMOV WHERE NSEQITMMOV IN (
	SELECT NSEQITMMOV FROM TITMMOVCOMPL WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND IDMOV = TMOV.IDMOV AND TITMMOVCOMPL.PRDREVENDA = 'SIM')
	AND CODCOLIGADA = TMOV.CODCOLIGADA
	AND IDMOV = TMOV.IDMOV)) CODIGOPRD,
			
	(SELECT CODIGOAUXILIAR FROM TPRODUTO WHERE CODCOLPRD = TMOV.CODCOLIGADA AND IDPRD IN 
	(SELECT IDPRD FROM TITMMOV WHERE NSEQITMMOV IN (
	SELECT NSEQITMMOV FROM TITMMOVCOMPL WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND IDMOV = TMOV.IDMOV AND TITMMOVCOMPL.PRDREVENDA = 'SIM')
	AND CODCOLIGADA = TMOV.CODCOLIGADA
	AND IDMOV = TMOV.IDMOV)) CODIGOAUXILIAR,
	
	(SELECT NUMEROCCF FROM TPRODUTO WHERE CODCOLPRD = TMOV.CODCOLIGADA AND IDPRD IN 
	(SELECT IDPRD FROM TITMMOV WHERE NSEQITMMOV IN (
	SELECT NSEQITMMOV FROM TITMMOVCOMPL WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND IDMOV = TMOV.IDMOV AND TITMMOVCOMPL.PRDREVENDA = 'SIM')
	AND CODCOLIGADA = TMOV.CODCOLIGADA
	AND IDMOV = TMOV.IDMOV)) NCM
	
FROM
	TMOV,
	TMOVCOMPL
WHERE
	TMOV.CODCOLIGADA = TMOVCOMPL.CODCOLIGADA
AND TMOV.IDMOV = TMOVCOMPL.IDMOV 
AND	TMOV.CODTMV = '2.1.03'
AND TMOVCOMPL.TIPOVENDA = 'T'
AND TMOV.STATUS = 'A'
AND TMOV.CODRPR = ? -- INSERIR PARAMETRO DO REPRESENTANTE
ORDER BY
	TMOVCOMPL.CODPRDREVENDA
	
	


", new object[] { codRPR, codRPR, codRPR, codRPR });

            if (dt.Rows.Count > 0)
            {
                DetailReport.DataSource = dt;
                xrCodRevenda.DataBindings.Add("Text", null, "CODPRDREVENDA");
                xrDescRevenda.DataBindings.Add("Text", null, "DESCRICAO_PRD");
                xrVlLiquido.DataBindings.Add("Text", null, "VALORLIQUIDOORIG", "{0:n2}");

                xrPercDesc.DataBindings.Add("Text", null, "PERC_DESC", "{0:n2}");
                xrValorDesc.DataBindings.Add("Text", null, "VALOR_DESC", "{0:n2}");
                xrValorCDesc.DataBindings.Add("Text", null, "VALOR_COM_DESCONTO", "{0:n2}");

                xrNCM.DataBindings.Add("Text", null, "NCM");
                xrCodProd.DataBindings.Add("Text", null, "CODIGOPRD");
                xrCodAux.DataBindings.Add("Text", null, "CODIGOAUXILIAR");
                xrAliquota.DataBindings.Add("Text", null, "ALIQ_IPI", "{0:n2}");
                xrIPI.DataBindings.Add("Text", null, "IPI", "{0:n2}");

                xrGrupoCliente.DataBindings.Add("Text", null, "CLIENTE");
                GroupHeader1.GroupFields.Add(new GroupField("CLIENTE"));
            }
            else
            {
                return;
            }
        }
    }
}
